server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:iot-jpa-vue   # For Test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8

  jpa:
    hibernate:
      # ddl-auto: update # 변경 사항만 수정
      ddl-auto: create-drop # 기존 테이블 삭제 후 새로 생성
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
